### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: main. Ошибка при запуске.

### ISSUE THREAD

**Issue by leshtaev-evgenii** [allure-framework/allure-android#15]
Добавил необходимые зависимости. Стартую тесты и получаю ошибку. Лог добавлен ниже
![2](https://user-images.githubusercontent.com/47177471/60897224-5ce41880-a270-11e9-8a06-f1bcae851098.png)

Logcat
java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{ru.app.test/ru.tinkoff.allure.android.AllureAndroidRunner}: java.lang.IllegalArgumentException: Failed to create: ru.tinkoff.allure.android.AllureAndroidListener
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5946)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalArgumentException: Failed to create: ru.tinkoff.allure.android.AllureAndroidListener
        at android.support.test.internal.runner.RunnerArgs$Builder.loadClassByNameInstantiateAndAdd(RunnerArgs.java:584)
        at android.support.test.internal.runner.RunnerArgs$Builder.parseLoadAndInstantiateClasses(RunnerArgs.java:502)
        at android.support.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:243)
        at android.support.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:331)
        at android.support.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:275)
        at ru.tinkoff.allure.android.AllureAndroidRunner.onCreate(AllureAndroidRunner.kt:20)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5941)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.support.test.internal.runner.RunnerArgs$Builder.loadClassByNameInstantiateAndAdd(RunnerArgs.java:572)
        at android.support.test.internal.runner.RunnerArgs$Builder.parseLoadAndInstantiateClasses(RunnerArgs.java:502) 
        at android.support.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:243) 
        at android.support.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:331) 
        at android.support.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:275) 
        at ru.tinkoff.allure.android.AllureAndroidRunner.onCreate(AllureAndroidRunner.kt:20) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5941) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
        at ru.tinkoff.allure.serialization.gson.GsonSerializationProcessor.<clinit>(GsonSerializationProcessor.kt:16)
        at ru.tinkoff.allure.io.FileSystemResultsReader.<init>(FileSystemResultsReader.kt:13)
        at ru.tinkoff.allure.android.AllureAndroidLifecycle.<init>(AllureAndroidLifecycle.kt:16)
        at ru.tinkoff.allure.android.AllureAndroidLifecycle.<clinit>(AllureAndroidLifecycle.kt:15)
        at ru.tinkoff.allure.android.AllureAndroidListener.<init>(AllureAndroidListener.kt:16)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.support.test.internal.runner.RunnerArgs$Builder.loadClassByNameInstantiateAndAdd(RunnerArgs.java:572) 
        at android.support.test.internal.runner.RunnerArgs$Builder.parseLoadAndInstantiateClasses(RunnerArgs.java:502) 
        at android.support.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:243) 
        at android.support.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:331) 
        at android.support.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:275) 
        at ru.tinkoff.allure.android.AllureAndroidRunner.onCreate(AllureAndroidRunner.kt:20) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5941) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/ru.app.test-y3H31zAIqQgtDz0DLr_95g==/base.apk", zip file "/data/app/ru.app-M40-5lK-yEQ6rdQ4-Vf7_w==/base.apk"],nativeLibraryDirectories=[/data/app/ru.app.test-y3H31zAIqQgtDz0DLr_95g==/lib/arm64, /data/app/ru.app-M40-5lK-yEQ6rdQ4-Vf7_w==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at ru.tinkoff.allure.serialization.gson.GsonSerializationProcessor.<clinit>(GsonSerializationProcessor.kt:16) 
        at ru.tinkoff.allure.io.FileSystemResultsReader.<init>(FileSystemResultsReader.kt:13) 
        at ru.tinkoff.allure.android.AllureAndroidLifecycle.<init>(AllureAndroidLifecycle.kt:16) 
        at ru.tinkoff.allure.android.AllureAndroidLifecycle.<clinit>(AllureAndroidLifecycle.kt:15) 
        at ru.tinkoff.allure.android.AllureAndroidListener.<init>(AllureAndroidListener.kt:16) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.support.test.internal.runner.RunnerArgs$Builder.loadClassByNameInstantiateAndAdd(RunnerArgs.java:572) 
        at android.support.test.internal.runner.RunnerArgs$Builder.parseLoadAndInstantiateClasses(RunnerArgs.java:502) 
        at android.support.test.internal.runner.RunnerArgs$Builder.fromBundle(RunnerArgs.java:243) 
        at android.support.test.runner.AndroidJUnitRunner.parseRunnerArgs(AndroidJUnitRunner.java:331) 
        at android.support.test.runner.AndroidJUnitRunner.onCreate(AndroidJUnitRunner.java:275) 
        at ru.tinkoff.allure.android.AllureAndroidRunner.onCreate(AllureAndroidRunner.kt:20) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5941) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
07-08 23:25:56.371 20542-20542/ru.app I/Process: Sending signal. PID: 20542 SIG: 9

**Comment by viclovsky** [comment]
Hello, @leshtaev-evgenii, old version, without AndroidX, now not supported. Please, check README.md and try [2.0.0](https://bintray.com/qameta/maven/allure-android/2.0.0) version, thanks.
