### ISSUE TITLE
Crash (as Null object reference) 

### ISSUE THREAD

**Issue by psychonuggets** [allure-framework/allure-android#17]
Every time when tests start I give this error:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.UiAutomation android.app.Instrumentation.getUiAutomation(int)' on a null object reference
at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at ru.tinkoff.allure.android.AllureAndroidListener.grantPermissions(AllureAndroidListener.kt:63)
at ru.tinkoff.allure.android.AllureAndroidListener.testRunStarted(AllureAndroidListener.kt:37)
at org.junit.runner.notification.SynchronizedRunListener.testRunStarted(SynchronizedRunListener.java:35)
at org.junit.runner.notification.RunNotifier$1.notifyListener(RunNotifier.java:91)
at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
at org.junit.runner.notification.RunNotifier.fireTestRunStarted(RunNotifier.java:88)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:389)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1948)
```

**Comment by viclovsky** [comment]
Hi,  @psychonuggets 

Unfortunately, andoidX isn't supported in version  2.5.1. 
But I have already fixed it and it will appear in nearest release. 

Thanks, 
Victor

**Comment by psychonuggets** [comment]
Thank's a lot.
When can expect a new version?
Thank you very much for this product.

**Comment by dkorobtsov** [comment]
Btw, same question - is there any plans to release androidx support any time soon? :-)

**Comment by viclovsky** [comment]
Hi, @dkorobtsov @psychonuggets  . New version with support AndroidX (BETA), available [here](https://bintray.com/qameta/maven/allure-android/2.0.0-beta1).  Please, look at README.md.

**Comment by psychonuggets** [comment]
> build.gradle
```
android {
    **minSdkVersion 16**
    testInstrumentationRunner "io.qameta.allure.espresso.AllureAndroidRunner"
}
dependencies {
    androidTestImplementation "io.qameta.allure:allure-android-commons:2.0.0-beta1"
    androidTestImplementation "io.qameta.allure:allure-android-model:2.0.0-beta1"
    androidTestImplementation "io.qameta.allure:allure-espresso:2.0.0-beta1"
    androidTestImplementation "androidx.test.uiautomator:uiautomator:2.2.0"
    }
repositories {
    mavenCentral()
    maven { url 'https://dl.bintray.com/qameta/maven' }
}
```

> AndroidManifest.xml
`<uses-sdk tools:overrideLibrary="android.support.test.uiautomator.v18" />`
or
`<uses-sdk tools:overrideLibrary="android.support.test.uiautomator.v18" />`
or
`<uses-sdk tools:overrideLibrary="io.qameta.allure.android" />`
or
`<uses-sdk tools:overrideLibrary="androidx.test.uiautomator.v18"/>`

or together

**Get an error**:
```
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [io.qameta.allure:allure-espresso:2.0.0-beta1] /Users/test/.gradle/caches/transforms-1/files-1.1/allure-espresso-2.0.0-beta1.aar/f2918773c39c0be79b394887d2833abd/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 18,
		or use tools:overrideLibrary="io.qameta.allure.android" to force usage (may lead to runtime failures)
```

### Previously used and and **everything was ok**:

> build.gradle
```
android {
    **minSdkVersion 16**
    testInstrumentationRunner "ru.tinkoff.allure.android.AllureAndroidRunner"
}
dependencies {
    androidTestImplementation "ru.tinkoff.allure:allure-android:2.5.1@aar"
    androidTestImplementation "ru.tinkoff.allure:allure-common:2.5.1"
    androidTestImplementation "ru.tinkoff.allure:allure-model:2.5.1"
    implementation "com.android.support.test.uiautomator:uiautomator-v18:2.1.3"
    }
repositories {
    mavenCentral()
}
```

> AndroidManifest.xml
`<uses-sdk tools:overrideLibrary="android.support.test.uiautomator.v18" />`



**Help me please :)**
